import pyautogui
import time
time.sleep(4)
pyautogui.typewrite('okaeri')
time.sleep(2)
pyautogui.press('enter')
time.sleep(2)
pyautogui.press('enter')
time.sleep(4)
pyautogui.typewrite('kyoumo')
time.sleep(2)
pyautogui.press('enter')
time.sleep(2)
pyautogui.press('enter')
time.sleep(4)
pyautogui.typewrite('otsukaresama')
time.sleep(2)
pyautogui.press('enter')
time.sleep(2)
pyautogui.press('enter')
time.sleep(4)
pyautogui.typewrite('yokuganbarimashita!!!')
time.sleep(2)
pyautogui.press('enter')
time.sleep(2)
pyautogui.press('enter')
